// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import * as dotenv from "dotenv";
import path from "path";
import { defineConfig, env } from "prisma/config";

const stage = process.env.NODE_ENV || "dev";

dotenv.config({ path: path.resolve(__dirname, `../../.env.${stage}`) });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
